# xi. Model Inference

In [2]:
import pickle
import pandas as pd
import numpy as np
import random

In [3]:
#load model scaler dan model knn yang sudah disimpen dalam bentuk pkl
with open('../models/scaler.pkl', 'rb') as file_1:
  scaler = pickle.load(file_1)

with open('../models/model_knn.pkl', 'rb') as file_2:
  model_knn = pickle.load(file_2)

## Membuat data dummy

In [4]:
# Atur seed di sini
seed_value = 777
random.seed(seed_value)
np.random.seed(seed_value)

# Jumlah data point yang ingin dibuat
n = 100

# Membuat data untuk kolom 'distance'
limit_balance = np.round(np.random.uniform(10000, 800000, n), 2)

# Membuat data untuk kolom 'surge_multiplier'
pay_1 = [-2.0,-1.0,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0]
pay_1 = random.choices(pay_1, k=n)

pay_2 = [-2.0,-1.0,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0]
pay_2 = random.choices(pay_2, k=n)

pay_3 = [-2.0,-1.0,0.0,2.0,3.0,4.0,5.0,6.0,7.0]
pay_3 = random.choices(pay_3, k=n)

pay_4 = [-2.0,-1.0,0.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0]
pay_4 = random.choices(pay_4, k=n)

pay_5 = [-2.0,-1.0,0.0,2.0,3.0,4.0,5.0,6.0,7.0]
pay_5 = random.choices(pay_5, k=n)

pay_6 = [-2.0,-1.0,0.0,2.0,3.0,4.0,6.0,7.0]
pay_6 = random.choices(pay_6, k=n)

# Membuat DataFrame
df_inf = pd.DataFrame({
    'limit_balance': limit_balance,
    'pay_1': pay_1,
    'pay_2': pay_2,
    'pay_3': pay_3,
    'pay_4': pay_4,
    'pay_5': pay_5,
    'pay_6': pay_6,
    
})

In [4]:
df_inf

    limit_balance  pay_1  pay_2  pay_3  pay_4  pay_5  pay_6
0       130604.35    0.0    7.0    5.0    5.0    2.0    6.0
1       248861.72    2.0   -2.0    3.0    0.0   -2.0    6.0
2        59008.77    2.0   -2.0    3.0    5.0    2.0    7.0
3       373289.67    0.0    7.0    2.0    2.0   -2.0    0.0
4       669850.17    1.0    4.0   -1.0    0.0    7.0    7.0
..            ...    ...    ...    ...    ...    ...    ...
95      772548.37    2.0   -2.0    0.0    0.0    6.0    3.0
96      780417.84    7.0    6.0    7.0    5.0    3.0   -2.0
97      169988.27    4.0    2.0    3.0   -2.0   -1.0    4.0
98      547083.91    4.0    1.0    4.0   -1.0    5.0    2.0
99      377622.60   -2.0    5.0    3.0    7.0    3.0    7.0

[100 rows x 7 columns]

In [5]:
#membagi 2 kolom numerical dan kategorical
df_inf_num = df_inf[['limit_balance']]
df_inf_cat= df_inf[['pay_1', 'pay_2', 'pay_3', 'pay_4','pay_5','pay_6']]

print(df_inf_cat)
print(df_inf_num)

    pay_1  pay_2  pay_3  pay_4  pay_5  pay_6
0     0.0    7.0    5.0    5.0    2.0    6.0
1     2.0   -2.0    3.0    0.0   -2.0    6.0
2     2.0   -2.0    3.0    5.0    2.0    7.0
3     0.0    7.0    2.0    2.0   -2.0    0.0
4     1.0    4.0   -1.0    0.0    7.0    7.0
..    ...    ...    ...    ...    ...    ...
95    2.0   -2.0    0.0    0.0    6.0    3.0
96    7.0    6.0    7.0    5.0    3.0   -2.0
97    4.0    2.0    3.0   -2.0   -1.0    4.0
98    4.0    1.0    4.0   -1.0    5.0    2.0
99   -2.0    5.0    3.0    7.0    3.0    7.0

[100 rows x 6 columns]
    limit_balance
0       130604.35
1       248861.72
2        59008.77
3       373289.67
4       669850.17
..            ...
95      772548.37
96      780417.84
97      169988.27
98      547083.91
99      377622.60

[100 rows x 1 columns]

## Scaling

In [6]:
df_inf_num_scaled = scaler.transform(df_inf_num)
df_inf_num_scaled=pd.DataFrame(df_inf_num_scaled)
df_inf_num_scaled

           0
0   0.241209
1   0.477723
2   0.098018
3   0.726579
4   1.319700
..       ...
95  1.525097
96  1.540836
97  0.319977
98  1.074168
99  0.735245

[100 rows x 1 columns]

## Menggabungkan 2 kolom numerikal yang sudah di scaling dan kolom kategorical

In [7]:
df_inf_final = np.concatenate([df_inf_num_scaled,df_inf_cat],axis = 1)
df_inf_final

array([[ 0.2412087 ,  0.        ,  7.        ,  5.        ,  5.        ,
         2.        ,  6.        ],
       [ 0.47772344,  2.        , -2.        ,  3.        ,  0.        ,
        -2.        ,  6.        ],
       [ 0.09801754,  2.        , -2.        ,  3.        ,  5.        ,
         2.        ,  7.        ],
       [ 0.72657934,  0.        ,  7.        ,  2.        ,  2.        ,
        -2.        ,  0.        ],
       [ 1.31970034,  1.        ,  4.        , -1.        ,  0.        ,
         7.        ,  7.        ],
       [ 1.46465534,  6.        ,  0.        ,  7.        ,  6.        ,
         4.        ,  3.        ],
       [ 1.1486426 ,  8.        , -1.        , -2.        ,  5.        ,
         5.        ,  3.        ],
       [ 1.21422404,  8.        ,  6.        ,  5.        ,  4.        ,
         4.        ,  3.        ],
       [ 0.425344  ,  4.        ,  4.        ,  5.        ,  2.        ,
         0.        ,  3.        ],
       [ 1.01756628,  2.        ,  2.        ,  3.        ,  2.        ,
         2.        ,  7.        ],
       [ 0.14752974,  1.        ,  3.        ,  7.        ,  5.        ,
         2.        ,  3.        ],
       [ 0.1259037 ,  8.        ,  3.        ,  0.        ,  3.        ,
         3.        ,  0.        ],
       [ 0.93158974,  8.        ,  5.        ,  5.        ,  8.        ,
         4.        ,  2.        ],
       [ 0.54247806,  5.        ,  1.        ,  4.        ,  3.        ,
         7.        ,  6.        ],
       [ 1.56242432,  7.        , -2.        ,  3.        ,  6.        ,
         0.        , -2.        ],
       [ 0.98982766, -1.        ,  7.        ,  4.        ,  0.        ,
         5.        , -1.        ],
       [ 1.07721126,  6.        , -1.        ,  5.        ,  4.        ,
         4.        ,  6.        ],
       [ 0.87256576,  8.        , -1.        ,  4.        ,  5.        ,
        -2.        ,  2.        ],
       [ 0.4247989 , -2.        ,  2.        ,  3.        ,  8.        ,
         7.        , -1.        ],
       [ 0.58974984,  5.        ,  1.        ,  0.        ,  5.        ,
         6.        ,  3.        ],
       [ 0.3522264 ,  1.        ,  0.        ,  4.        ,  5.        ,
         3.        , -1.        ],
       [ 0.2945793 ,  4.        ,  5.        ,  5.        , -2.        ,
         7.        ,  3.        ],
       [ 0.61722398, -1.        ,  6.        ,  5.        , -1.        ,
        -1.        ,  3.        ],
       [ 0.3051966 ,  5.        ,  4.        ,  5.        ,  0.        ,
         3.        ,  2.        ],
       [ 0.96523928,  0.        ,  2.        , -2.        ,  6.        ,
         3.        ,  4.        ],
       [ 1.39483734,  3.        , -2.        ,  4.        ,  2.        ,
         4.        ,  4.        ],
       [ 0.98329534,  6.        , -2.        ,  7.        ,  5.        ,
         4.        ,  7.        ],
       [ 0.39992794,  7.        ,  0.        , -2.        ,  7.        ,
         5.        , -1.        ],
       [ 0.28428988,  4.        ,  6.        ,  3.        , -2.        ,
         6.        ,  7.        ],
       [ 1.28991906, -2.        , -2.        ,  2.        ,  8.        ,
         6.        ,  2.        ],
       [ 0.35608716,  4.        ,  4.        ,  4.        ,  6.        ,
        -1.        ,  6.        ],
       [ 0.81663428,  4.        , -2.        ,  6.        , -1.        ,
         0.        , -1.        ],
       [ 0.8192234 , -2.        , -2.        ,  6.        ,  5.        ,
         2.        ,  0.        ],
       [ 0.9485924 ,  4.        ,  3.        ,  7.        ,  3.        ,
        -2.        ,  7.        ],
       [ 0.84154036,  1.        ,  4.        , -1.        , -1.        ,
         0.        ,  4.        ],
       [ 0.02102988,  6.        ,  7.        ,  4.        , -1.        ,
         0.        ,  7.        ],
       [ 0.82807368,  3.        ,  2.        , -1.        ,  6.        ,
         2.        ,  3.        ],
       [ 1.41549784,  4.        , -1.        ,  3.        ,  8.        ,
         0.        , -1.        ],
       [ 1.21644404, -1.        ,  2.        , -1.        ,  6.        ,
         6.        , -2.        ],
       [ 0.19410568,  2.        ,  6.        ,  5.        ,  4.        ,
         3.        ,  3.        ],
       [ 0.46747886,  0.        ,  3.        , -2.        ,  5.        ,
         4.        ,  0.        ],
       [ 0.96699726,  4.        ,  1.        ,  7.        ,  5.        ,
         0.        , -2.        ],
       [ 1.14729824, -2.        ,  0.        ,  4.        ,  6.        ,
         2.        ,  2.        ],
       [ 0.732326  , -1.        ,  6.        , -1.        ,  3.        ,
         5.        ,  0.        ],
       [ 1.21519438,  8.        ,  7.        ,  6.        ,  0.        ,
         6.        ,  4.        ],
       [ 0.30277702,  6.        ,  6.        ,  5.        ,  2.        ,
         0.        ,  3.        ],
       [ 0.88142942,  3.        ,  0.        , -1.        , -1.        ,
         6.        ,  6.        ],
       [ 0.87022948,  7.        ,  6.        , -1.        ,  8.        ,
         2.        ,  6.        ],
       [ 0.74611628,  8.        ,  1.        ,  4.        ,  5.        ,
         7.        ,  7.        ],
       [ 1.25117824,  1.        ,  4.        ,  2.        ,  6.        ,
         0.        ,  3.        ],
       [ 0.1820945 ,  8.        ,  0.        ,  3.        ,  6.        ,
         5.        ,  4.        ],
       [ 1.07646016,  8.        ,  6.        ,  3.        ,  2.        ,
         5.        ,  0.        ],
       [ 0.5724871 , -1.        ,  1.        ,  5.        ,  7.        ,
         2.        ,  6.        ],
       [ 0.54385006,  7.        ,  7.        ,  4.        ,  7.        ,
         2.        ,  2.        ],
       [ 0.71023962, -2.        ,  2.        ,  4.        , -1.        ,
         2.        ,  6.        ],
       [ 0.04256878,  8.        ,  0.        ,  7.        ,  7.        ,
         0.        ,  2.        ],
       [ 0.65609134,  4.        ,  0.        ,  7.        , -2.        ,
         4.        ,  4.        ],
       [ 1.4571261 ,  0.        , -2.        ,  4.        ,  2.        ,
        -2.        ,  2.        ],
       [ 0.1441048 ,  0.        ,  0.        ,  2.        ,  4.        ,
         4.        , -2.        ],
       [ 0.49789242, -2.        ,  3.        ,  6.        ,  6.        ,
         7.        ,  0.        ],
       [ 0.83427514,  5.        , -1.        , -2.        ,  0.        ,
         7.        ,  0.        ],
       [ 0.518338  ,  6.        ,  2.        ,  3.        ,  8.        ,
         3.        ,  0.        ],
       [ 0.70928656,  5.        ,  1.        ,  3.        , -1.        ,
         6.        , -2.        ],
       [ 0.02580838,  2.        ,  2.        ,  0.        , -1.        ,
         7.        ,  3.        ],
       [ 0.1533025 ,  5.        ,  1.        ,  7.        ,  5.        ,
         7.        ,  6.        ],
       [ 1.09428994,  3.        ,  5.        ,  4.        , -2.        ,
        -1.        ,  4.        ],
       [ 1.32079058,  2.        ,  0.        ,  3.        ,  2.        ,
         5.        ,  2.        ],
       [ 0.67042874,  2.        ,  2.        , -1.        ,  8.        ,
        -1.        , -1.        ],
       [ 1.3410634 ,  1.        ,  6.        ,  7.        ,  8.        ,
         6.        , -1.        ],
       [ 0.86393012,  5.        ,  5.        , -2.        ,  7.        ,
         0.        ,  4.        ],
       [ 0.55948346,  4.        ,  5.        ,  6.        ,  6.        ,
        -2.        ,  6.        ],
       [ 1.1490545 ,  1.        ,  2.        ,  5.        ,  4.        ,
         6.        , -2.        ],
       [ 0.14828566,  3.        , -2.        ,  5.        ,  0.        ,
         0.        ,  4.        ],
       [ 1.4107169 ,  3.        ,  4.        , -2.        ,  8.        ,
         0.        ,  0.        ],
       [ 0.53128808,  4.        ,  4.        ,  4.        , -2.        ,
         7.        ,  4.        ],
       [ 1.40909564, -2.        ,  0.        ,  7.        , -2.        ,
         7.        ,  3.        ],
       [ 0.46902142,  7.        ,  5.        ,  6.        ,  6.        ,
         5.        ,  2.        ],
       [ 0.4766043 ,  1.        ,  7.        ,  5.        ,  5.        ,
         4.        ,  3.        ],
       [ 1.27386016,  4.        ,  1.        ,  6.        , -2.        ,
         7.        , -1.        ],
       [ 1.32342374,  8.        ,  5.        ,  7.        , -2.        ,
         6.        ,  2.        ],
       [ 1.0021645 ,  5.        ,  1.        , -1.        ,  4.        ,
         5.        ,  4.        ],
       [ 0.49189714, -1.        , -1.        ,  3.        ,  3.        ,
         2.        ,  7.        ],
       [ 0.04652876,  1.        , -2.        ,  7.        ,  7.        ,
         5.        ,  0.        ],
       [ 0.63164816,  5.        ,  1.        , -2.        ,  3.        ,
        -1.        , -2.        ],
       [ 0.81871406,  5.        ,  6.        ,  7.        ,  2.        ,
        -1.        ,  7.        ],
       [ 0.01167376,  7.        ,  1.        , -2.        ,  4.        ,
         0.        ,  4.        ],
       [ 1.22441748,  8.        , -1.        , -2.        ,  8.        ,
         0.        ,  6.        ],
       [ 1.35006448, -2.        ,  2.        ,  5.        ,  3.        ,
         7.        , -2.        ],
       [ 0.20782186,  1.        ,  6.        ,  2.        ,  8.        ,
         6.        ,  4.        ],
       [ 0.45452436,  1.        ,  5.        ,  3.        ,  8.        ,
         3.        , -1.        ],
       [ 0.51601032,  5.        ,  7.        , -1.        ,  7.        ,
         7.        , -1.        ],
       [ 1.4323641 , -1.        ,  6.        , -2.        , -2.        ,
         2.        ,  7.        ],
       [ 1.57930408,  1.        , -1.        ,  5.        ,  6.        ,
         2.        , -1.        ],
       [ 1.21799718,  8.        ,  6.        ,  6.        ,  2.        ,
         4.        ,  3.        ],
       [ 0.06769908,  0.        ,  2.        ,  7.        ,  7.        ,
         3.        ,  3.        ],
       [ 1.52509674,  2.        , -2.        ,  0.        ,  0.        ,
         6.        ,  3.        ],
       [ 1.54083568,  7.        ,  6.        ,  7.        ,  5.        ,
         3.        , -2.        ],
       [ 0.31997654,  4.        ,  2.        ,  3.        , -2.        ,
        -1.        ,  4.        ],
       [ 1.07416782,  4.        ,  1.        ,  4.        , -1.        ,
         5.        ,  2.        ],
       [ 0.7352452 , -2.        ,  5.        ,  3.        ,  7.        ,
         3.        ,  7.        ]])

In [9]:
#membuat kolom predict 
y_pred_inf = model_knn.predict(df_inf_final)
y_pred_inf

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [10]:
#membuat kolom predict kedalam data frame dan memberi nama kolomnya dengan 'Def_payment - Prediction'
y_pred_inf_df = pd.DataFrame(y_pred_inf, columns=['Def_payment - Prediction'])
y_pred_inf_df

    Def_payment - Prediction
0                          0
1                          1
2                          0
3                          1
4                          1
..                       ...
95                         1
96                         1
97                         1
98                         1
99                         1

[100 rows x 1 columns]

In [10]:
#membuat variabel baru dengan menggabungkan 2 tabel yaitu df_inf dan y _preditc inf
tabel_inference = pd.concat([df_inf, y_pred_inf_df], axis=1)
tabel_inference

,limit_balance,pay_1,pay_2,pay_3,pay_4,pay_5,pay_6,Def_payment - Prediction
0,130604.35,0.0,7.0,5.0,5.0,2.0,6.0,0
1,248861.72,2.0,-2.0,3.0,0.0,-2.0,6.0,1
2,59008.77,2.0,-2.0,3.0,5.0,2.0,7.0,0
3,373289.67,0.0,7.0,2.0,2.0,-2.0,0.0,1
4,669850.17,1.0,4.0,-1.0,0.0,7.0,7.0,1
...,...,...,...,...,...,...,...,...
95,772548.37,2.0,-2.0,0.0,0.0,6.0,3.0,1
96,780417.84,7.0,6.0,7.0,5.0,3.0,-2.0,1
97,169988.27,4.0,2.0,3.0,-2.0,-1.0,4.0,1
98,547083.91,4.0,1.0,4.0,-1.0,5.0,2.0,1
99,377622.60,-2.0,5.0,3.0,7.0,3.0,7.0,1

# xii. Kesimpulan

- Saya memilih f1 score sebagai parameter score karena menurut saya untuk meminimalisir false postive dan false negative penting .

- Dari hasil std yang mendekati 0 dan berada di bawah mean berarti model KNN yang default nilai STD 0.03 sehingga modelnya best fit . Jadi bisa dikatakan bahwa model knn default memiliki konsistensi yang bagus akan tetapi validasi hasil predictnya kurang bagus dikarenakan hanya sekitar 48%. Dari sisi bisnis model ini belum bisa digunakan karena hasil predictnya yang masih kurang bagus kurang dari 50% sehingga bisa menimbulkan hasil predict yang salah dimana bisa menyebabkan perusahaan rugi.

- Untuk Meningkatkan jumlah user yang bisa bayar ada baiknya untuk penagihan bisa dilakukan ditanggal gajian sekitar 25-31 pada saat gajian karena pada saat tanggal tersebut uang mereka jumlahnya banyak jadi bisa membayar

## Conceptual Problems :

1. Apakah yang dimaksud dengan coeficient pada logistic regression?

Yang dimaksud dengan coeficient pada logistic regression adalah nilai bobot atau parameter yang digunakan untuk mengukur hubungan antara variabel independen (fitur) dengan variabel dependen (kelas atau target)

2. Apakah fungsi parameter kernel pada SVM? Jelaskan salah satu kernel yang kalian pahami!

Kernel adalah fungsi matematis yang digunakan untuk mengukur kesamaan antara pasangan data dalam ruang fitur
Salah satu kernelnya adalah linear yang digunakan untuk pemisahan data yang dapat dipisahkan dengan garis lurus.

3. Bagaimana cara memilih K yang optimal pada KNN ?

Cara memilih K yang optimal pada KNN adalah dengan membagi data set menjadi 2 yaitu train dan test lalu mendefine model knn. Lalu diolah dengan menggunakan cross validation untuk menentukan parameter mana yang terbaik dan memvariasikan nilai K dan mengamati performa validasi silang, kita bisa menemukan K yang optimal

4. Apa yang dimaksud dengan metrics-metrics berikut : Accuracy, Precision, Recall, F1 Score, dan kapan waktu yang tepat untuk menggunakannya ?

Accuracy: Merupakan rasio dari jumlah prediksi yang benar (positif dan negatif) dibandingkan dengan jumlah total sampel. Berguna ketika distribusi kelas seimbang. Namun, bisa menjadi bias jika kelas tidak seimbang.

Precision: Merupakan rasio dari jumlah prediksi positif yang benar dibandingkan dengan total prediksi positif. Berguna ketika penting untuk menghindari false positive.

Recall: Merupakan rasio dari jumlah prediksi positif yang benar dibandingkan dengan total jumlah sampel positif yang sebenarnya. Berguna ketika penting untuk menghindari false negative.

F1 Score: Merupakan ukuran yang mengkombinasikan precision dan recall. Berguna ketika Anda ingin mencari keseimbangan antara precision dan recall.